### ISSUE TITLE
PirateNZB

### ISSUE THREAD

**Issue by albino1** [pillone/usntssearch#157]
Mirabis,

First I just wanted to say thanks for the changes you made a few weeks ago to NZBM.  I don't think there's an auto-update feature, so I just now noticed them in the commit log.

I went ahead and updated by hand, and filled in my credentials for PirateNZB, but it doesn't appear to even be attempting to search the indexer.

In the example below I enabled all three of the "Other NZB engines":

![al-nzbm-1](https://cloud.githubusercontent.com/assets/12164957/9292391/ec498cc2-43aa-11e5-9582-b66d6265dcf8.jpg)

Then I ran an example search and it says it's searching 3 providers:

![al-nzbm-2](https://cloud.githubusercontent.com/assets/12164957/9292394/11083bc6-43ab-11e5-912c-6b3cf5d95cb9.jpg)

But there are no results from PirateNZB, and when I check the connectivity log it only shows OMGWTFNZBS and GingaDaddy being searched:

![al-nzbm-3](https://cloud.githubusercontent.com/assets/12164957/9292397/421abfea-43ab-11e5-9797-702f3ba9281f.jpg)

If I enable PirateNZB only then it says:

 `0 total (0 failed, 0 successful)`

Let me know if I'm missing anything obvious.  Thanks!

**Comment by albino1** [comment]
Here's some additional info from the log:

```
2015-08-16 13:29:23,776 - TERMINAL_ERR - ERROR - KeyError: 'nzbguid'
2015-08-16 13:29:23,776 - TERMINAL_ERR - ERROR - 'url': 'https://piratenzb.com/api?apikey='+cfg['pwd']+'&t=get&id='+ str(data[i]['nzbguid']),
2015-08-16 13:29:23,776 - TERMINAL_ERR - ERROR - File "C:\Program Files (x86)\NZBMegaSearch\NZBMegaSearch\SearchModules\am_PirateNzb.py", line 92, in search
2015-08-16 13:29:23,776 - TERMINAL_ERR - ERROR - localResults = neededModule.search(queryString, cfg)
2015-08-16 13:29:23,776 - TERMINAL_ERR - ERROR - File "C:\Program Files (x86)\NZBMegaSearch\NZBMegaSearch\SearchModule.py", line 242, in performSearchThread
2015-08-16 13:29:23,776 - TERMINAL_ERR - ERROR - self.__target(*self.__args, **self.__kwargs)
2015-08-16 13:29:23,776 - TERMINAL_ERR - ERROR - File "C:\Program Files\Python27\lib\threading.py", line 763, in run
2015-08-16 13:29:23,776 - TERMINAL_ERR - ERROR - self.run()
2015-08-16 13:29:23,776 - TERMINAL_ERR - ERROR - File "C:\Program Files\Python27\lib\threading.py", line 810, in __bootstrap_inner
2015-08-16 13:29:23,776 - TERMINAL_ERR - ERROR - Traceback (most recent call last):
2015-08-16 13:29:23,776 - TERMINAL_ERR - ERROR - Exception in thread Thread-19: 
```

**Comment by Mirabis** [comment]
Yeh, better off adding the 'api' variant of PirateNZB : )

**Comment by SimplyNZBs** [comment]
Should now work with PirateNZB

**Comment by Mirabis** [comment]
Might be handy to notify the nzbHydra guys too :palm_tree:

**Comment by SimplyNZBs** [comment]
Have just let them know :)

**Comment by albino1** [comment]
Confirmed, it's working in NZBMegaSearch now with just the regular NN API option, so no need for the special plugin.  Thanks @PirateNZB!
